### PR TITLE
Tests for mm symbolic representation

### PR DESCRIPTION
**Pull request by jamesr66a**
This provides correctness testing for https://github.com/pytorch/pytorch/pull/3290

### CODE REVIEW

**Comment by houseroad** [comment]
Same here, probably after the changes in PyTorch get merged, you can update this PR. We have CI, but it is broken now.

**Comment by houseroad** [comment]
Any magic will happen?

**Comment by ezyang** [comment]
In the end, I did the close/reopen trick lol.

**Comment by houseroad** [comment]
So hard to summon @pytorchbot, bad boy.

**Comment by jamesr66a** [comment]
Anyone have insight into the operator test failures happening here? Are these legitimate outputs that I can --accept?

**Pull request merged**
