### PR TITLE
Tests for unfold ATen symbolic representation

### PR DESCRIPTION
**Pull request by jamesr66a**
Tests corresponding to https://github.com/pytorch/pytorch/pull/3334

### CODE REVIEW

**Comment by jamesr66a** [comment]
CI blocked on https://github.com/ezyang/onnx-pytorch/issues/33

**Comment by ezyang** [comment]
This isn't going to happen until we setup new Jenkins. Once we do, my plan for handling Caffe2 builds is to add a pipeline stage before onnx-pytorch which builds and installs Caffe2.

**Comment by ezyang** [comment]
This PR should now be on onnx-fb-universe.

**Pull request closed without merging**
